/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{svelte,ts,js}'],
  theme: {
    extend: {
      colors: {
        bg: {
          900: 'oklch(var(--n) / <alpha-value>)',
          800: 'oklch(var(--b1) / <alpha-value>)',
          700: 'oklch(var(--b2) / <alpha-value>)',
          600: 'oklch(var(--b3) / <alpha-value>)',
        },
        fg: {
          DEFAULT: 'oklch(var(--bc) / <alpha-value>)',
          dim: 'oklch(var(--bc) / 0.72)',
          mute: 'oklch(var(--bc) / 0.52)',
        },
        accent: {
          DEFAULT: 'oklch(var(--p) / <alpha-value>)',
          warn: 'oklch(var(--wa) / <alpha-value>)',
          err: 'oklch(var(--er) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
        mono: [
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Consolas',
          'monospace',
        ],
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        dia: {
          primary: '#7fdbca',
          'primary-content': '#1b2636',
          secondary: '#ecc48d',
          'secondary-content': '#1b2636',
          accent: '#ff5874',
          'accent-content': '#ffffff',
          neutral: '#2f3d52',
          'neutral-content': '#d6deeb',
          'base-100': '#1b2636',
          'base-200': '#243144',
          'base-300': '#2f3d52',
          'base-content': '#d6deeb',
          info: '#67b0e8',
          success: '#7fdbca',
          warning: '#ecc48d',
          error: '#ff5874',
        },
        'dia-light': {
          primary: '#e07c1f',
          'primary-content': '#fffcf0',
          secondary: '#7c3aed',
          'secondary-content': '#ffffff',
          accent: '#db2777',
          'accent-content': '#ffffff',
          neutral: '#57534e',
          'neutral-content': '#f5f0e8',
          'base-100': '#fffcf0',
          'base-200': '#faf3e8',
          'base-300': '#f0e6d4',
          'base-content': '#292524',
          info: '#0284c7',
          success: '#16a34a',
          warning: '#ca8a04',
          error: '#dc2626',
        },
      },
      'light',
      'dark',
      'cupcake',
      'bumblebee',
      'emerald',
      'corporate',
      'synthwave',
      'retro',
      'cyberpunk',
      'valentine',
      'halloween',
      'garden',
      'forest',
      'aqua',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'black',
      'luxury',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'acid',
      'lemonade',
      'night',
      'coffee',
      'winter',
      'dim',
      'nord',
      'sunset',
    ],
  },
};
