// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRoot(arg1) {
  return window['go']['wailsapp']['App']['AddRoot'](arg1);
}

export function DeleteCustomTheme(arg1) {
  return window['go']['wailsapp']['App']['DeleteCustomTheme'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['wailsapp']['App']['DeleteWorkspace'](arg1);
}

export function DetectTools() {
  return window['go']['wailsapp']['App']['DetectTools']();
}

export function Doctor() {
  return window['go']['wailsapp']['App']['Doctor']();
}

export function GetKeybindings() {
  return window['go']['wailsapp']['App']['GetKeybindings']();
}

export function GetPluginCapabilities(arg1) {
  return window['go']['wailsapp']['App']['GetPluginCapabilities'](arg1);
}

export function GetRecent() {
  return window['go']['wailsapp']['App']['GetRecent']();
}

export function GetTheme() {
  return window['go']['wailsapp']['App']['GetTheme']();
}

export function GetWorkspace(arg1) {
  return window['go']['wailsapp']['App']['GetWorkspace'](arg1);
}

export function GetWorkspaceEditor(arg1) {
  return window['go']['wailsapp']['App']['GetWorkspaceEditor'](arg1);
}

export function InspectPluginSource(arg1, arg2) {
  return window['go']['wailsapp']['App']['InspectPluginSource'](arg1, arg2);
}

export function InstallPluginFromFolder() {
  return window['go']['wailsapp']['App']['InstallPluginFromFolder']();
}

export function InstallPluginFromSource(arg1, arg2) {
  return window['go']['wailsapp']['App']['InstallPluginFromSource'](arg1, arg2);
}

export function ListCustomThemes() {
  return window['go']['wailsapp']['App']['ListCustomThemes']();
}

export function ListInstances() {
  return window['go']['wailsapp']['App']['ListInstances']();
}

export function ListPlugins() {
  return window['go']['wailsapp']['App']['ListPlugins']();
}

export function ListRoots() {
  return window['go']['wailsapp']['App']['ListRoots']();
}

export function ListWorkspaces() {
  return window['go']['wailsapp']['App']['ListWorkspaces']();
}

export function NewWorkspace(arg1, arg2) {
  return window['go']['wailsapp']['App']['NewWorkspace'](arg1, arg2);
}

export function OpenConfigFolder() {
  return window['go']['wailsapp']['App']['OpenConfigFolder']();
}

export function OpenPluginFolder() {
  return window['go']['wailsapp']['App']['OpenPluginFolder']();
}

export function OpenPluginWindow(arg1) {
  return window['go']['wailsapp']['App']['OpenPluginWindow'](arg1);
}

export function OpenStateFile() {
  return window['go']['wailsapp']['App']['OpenStateFile']();
}

export function OpenStateFolder() {
  return window['go']['wailsapp']['App']['OpenStateFolder']();
}

export function Paths() {
  return window['go']['wailsapp']['App']['Paths']();
}

export function PluginCall(arg1, arg2, arg3) {
  return window['go']['wailsapp']['App']['PluginCall'](arg1, arg2, arg3);
}

export function PluginIsUpdatable(arg1) {
  return window['go']['wailsapp']['App']['PluginIsUpdatable'](arg1);
}

export function PluginPaths() {
  return window['go']['wailsapp']['App']['PluginPaths']();
}

export function Reconcile() {
  return window['go']['wailsapp']['App']['Reconcile']();
}

export function RemoveRoot(arg1) {
  return window['go']['wailsapp']['App']['RemoveRoot'](arg1);
}

export function ResetKeybindings() {
  return window['go']['wailsapp']['App']['ResetKeybindings']();
}

export function RevealPath(arg1) {
  return window['go']['wailsapp']['App']['RevealPath'](arg1);
}

export function SaveWorkspaceEditor(arg1) {
  return window['go']['wailsapp']['App']['SaveWorkspaceEditor'](arg1);
}

export function SetCustomTheme(arg1) {
  return window['go']['wailsapp']['App']['SetCustomTheme'](arg1);
}

export function SetKeybinding(arg1, arg2) {
  return window['go']['wailsapp']['App']['SetKeybinding'](arg1, arg2);
}

export function SetPluginCapabilities(arg1, arg2) {
  return window['go']['wailsapp']['App']['SetPluginCapabilities'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['wailsapp']['App']['SetTheme'](arg1);
}

export function StartStateWatcher() {
  return window['go']['wailsapp']['App']['StartStateWatcher']();
}

export function StartWorkspace(arg1) {
  return window['go']['wailsapp']['App']['StartWorkspace'](arg1);
}

export function Startup(arg1) {
  return window['go']['wailsapp']['App']['Startup'](arg1);
}

export function StopAll() {
  return window['go']['wailsapp']['App']['StopAll']();
}

export function StopInstance(arg1) {
  return window['go']['wailsapp']['App']['StopInstance'](arg1);
}

export function StopWorkspace(arg1) {
  return window['go']['wailsapp']['App']['StopWorkspace'](arg1);
}

export function UninstallPlugin(arg1) {
  return window['go']['wailsapp']['App']['UninstallPlugin'](arg1);
}

export function UpdatePlugin(arg1) {
  return window['go']['wailsapp']['App']['UpdatePlugin'](arg1);
}
