// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCustomTheme(arg1) {
  return window['go']['wailsapp']['App']['DeleteCustomTheme'](arg1);
}

export function Doctor() {
  return window['go']['wailsapp']['App']['Doctor']();
}

export function GetTheme() {
  return window['go']['wailsapp']['App']['GetTheme']();
}

export function GetWorkspace(arg1) {
  return window['go']['wailsapp']['App']['GetWorkspace'](arg1);
}

export function ListCustomThemes() {
  return window['go']['wailsapp']['App']['ListCustomThemes']();
}

export function ListInstances() {
  return window['go']['wailsapp']['App']['ListInstances']();
}

export function ListWorkspaces() {
  return window['go']['wailsapp']['App']['ListWorkspaces']();
}

export function NewWorkspace(arg1) {
  return window['go']['wailsapp']['App']['NewWorkspace'](arg1);
}

export function OpenConfigFolder() {
  return window['go']['wailsapp']['App']['OpenConfigFolder']();
}

export function OpenStateFolder() {
  return window['go']['wailsapp']['App']['OpenStateFolder']();
}

export function Paths() {
  return window['go']['wailsapp']['App']['Paths']();
}

export function Reconcile() {
  return window['go']['wailsapp']['App']['Reconcile']();
}

export function SetCustomTheme(arg1) {
  return window['go']['wailsapp']['App']['SetCustomTheme'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['wailsapp']['App']['SetTheme'](arg1);
}

export function StartWorkspace(arg1) {
  return window['go']['wailsapp']['App']['StartWorkspace'](arg1);
}

export function Startup(arg1) {
  return window['go']['wailsapp']['App']['Startup'](arg1);
}

export function StopAll() {
  return window['go']['wailsapp']['App']['StopAll']();
}

export function StopInstance(arg1) {
  return window['go']['wailsapp']['App']['StopInstance'](arg1);
}
