// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailsapp} from '../models';
import {context} from '../models';

export function DeleteCustomTheme(arg1:string):Promise<void>;

export function Doctor():Promise<Array<wailsapp.CheckInfo>>;

export function GetTheme():Promise<string>;

export function GetWorkspace(arg1:string):Promise<wailsapp.WorkspaceDetail>;

export function ListCustomThemes():Promise<Array<wailsapp.CustomThemeInfo>>;

export function ListInstances():Promise<Array<wailsapp.InstanceInfo>>;

export function ListWorkspaces():Promise<Array<wailsapp.WorkspaceInfo>>;

export function NewWorkspace(arg1:string):Promise<string>;

export function OpenConfigFolder():Promise<void>;

export function OpenStateFolder():Promise<void>;

export function Paths():Promise<wailsapp.PathsInfo>;

export function Reconcile():Promise<wailsapp.ReconcileInfo>;

export function SetCustomTheme(arg1:wailsapp.CustomThemeInfo):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function StartWorkspace(arg1:string):Promise<wailsapp.InstanceInfo>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopAll():Promise<number>;

export function StopInstance(arg1:string):Promise<void>;
