// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailsapp} from '../models';
import {state} from '../models';
import {context} from '../models';

export function ClearProjectDir():Promise<void>;

export function DeleteCustomTheme(arg1:string):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function DetectTools():Promise<Array<wailsapp.ToolCategory>>;

export function DisablePlugin(arg1:string):Promise<void>;

export function Doctor():Promise<Array<wailsapp.CheckInfo>>;

export function EnablePlugin(arg1:string):Promise<void>;

export function GetKeybindings():Promise<Record<string, string>>;

export function GetProjectDir():Promise<string>;

export function GetRecent():Promise<Array<state.RecentEntry>>;

export function GetTheme():Promise<string>;

export function GetWorkspace(arg1:string):Promise<wailsapp.WorkspaceDetail>;

export function GetWorkspaceEditor(arg1:string):Promise<wailsapp.WorkspaceEditor>;

export function ListCustomThemes():Promise<Array<wailsapp.CustomThemeInfo>>;

export function ListInstances():Promise<Array<wailsapp.InstanceInfo>>;

export function ListPlugins():Promise<Array<wailsapp.PluginInfo>>;

export function ListWorkspaces():Promise<Array<wailsapp.WorkspaceInfo>>;

export function NewWorkspace(arg1:string,arg2:boolean):Promise<string>;

export function OpenConfigFolder():Promise<void>;

export function OpenPluginFolder():Promise<void>;

export function OpenPluginWindow(arg1:string):Promise<number>;

export function OpenStateFile():Promise<void>;

export function OpenStateFolder():Promise<void>;

export function Paths():Promise<wailsapp.PathsInfo>;

export function PluginCall(arg1:string,arg2:string,arg3:string):Promise<string>;

export function PluginPaths():Promise<wailsapp.PluginPathsInfo>;

export function Reconcile():Promise<wailsapp.ReconcileInfo>;

export function ResetKeybindings():Promise<void>;

export function RevealPath(arg1:string):Promise<void>;

export function SaveWorkspaceEditor(arg1:wailsapp.WorkspaceEditor):Promise<void>;

export function SelectProjectDir():Promise<string>;

export function SetCustomTheme(arg1:wailsapp.CustomThemeInfo):Promise<void>;

export function SetKeybinding(arg1:string,arg2:string):Promise<void>;

export function SetPluginEnabled(arg1:string,arg2:boolean,arg3:Array<string>):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function StartWorkspace(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopAll():Promise<number>;

export function StopInstance(arg1:string):Promise<void>;

export function StopWorkspace(arg1:string):Promise<void>;
